#!/usr/bin/env python3
"""
Fetch property geometry from Supabase PostGIS and write property_data.json.

Usage: python3 fetch_property_data.py
Output: blender/property_data.json

The Blender render script reads this JSON instead of hardcoding GPS coordinates.
Re-run whenever database geometry changes.
"""

import json
import os
import urllib.request

SUPABASE_URL = 'https://aphrrfprbixmhissnjfn.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwaHJyZnByYml4bWhpc3NuamZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MzA0MjUsImV4cCI6MjA4NTUwNjQyNX0.yYkdQIq97GQgxK7yT2OQEPi5Tt-a7gM45aF8xjSD6wk'

HEADERS = {
    'apikey': SUPABASE_ANON_KEY,
    'Authorization': f'Bearer {SUPABASE_ANON_KEY}',
    'Content-Type': 'application/json',
}


def rest_get(table, select='*', filters=''):
    """Query Supabase REST API."""
    url = f'{SUPABASE_URL}/rest/v1/{table}?select={select}'
    if filters:
        url += f'&{filters}'
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def rpc_call(fn_name, params=None):
    """Call a Supabase RPC function."""
    url = f'{SUPABASE_URL}/rest/v1/rpc/{fn_name}'
    data = json.dumps(params or {}).encode()
    req = urllib.request.Request(url, data=data, headers=HEADERS, method='POST')
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def fetch_with_geojson(table, geom_col, select_extra='', filters=''):
    """Fetch rows with a geometry column converted to GeoJSON text."""
    # PostGIS ST_AsGeoJSON via computed column isn't available in REST,
    # so we fetch raw and let the caller handle it.
    # Actually, Supabase REST doesn't expose PostGIS functions directly.
    # We'll use the raw REST API and the geometry comes as WKB hex.
    # Instead, we'll use an RPC or just fetch the non-geom columns
    # and rely on the Blender script to use the dimensional data.
    pass


def main():
    print('Fetching parcel data...')
    parcels = rest_get('parcels', select='*', filters='id=eq.1')
    parcel = parcels[0] if parcels else None

    print('Fetching parcel edges...')
    edges = rest_get('parcel_edges', select='*', filters='parcel_id=eq.1&order=edge_side')

    print('Fetching structures...')
    structures = rest_get('structures', select='*', filters='parcel_id=eq.1&is_active=eq.true&order=display_order')

    print('Fetching structure setbacks...')
    setbacks = rest_get('structure_setbacks', select='*')

    # Build output — geometry columns come as WKB hex from REST API.
    # If they're populated, the Blender script can parse them.
    # If NULL, the script falls back to dimensional placement.
    output = {
        '_comment': 'Auto-generated by fetch_property_data.py — do not edit manually',
        'parcel': parcel,
        'edges': edges,
        'structures': structures,
        'setbacks': setbacks,
    }

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'property_data.json')
    with open(out_path, 'w') as f:
        json.dump(output, f, indent=2, default=str)

    print(f'Wrote {out_path}')
    print(f'  Parcel: {parcel["name"] if parcel else "NOT FOUND"}')
    print(f'  Edges: {len(edges)}')
    print(f'  Structures: {len(structures)}')

    # Check geometry population status
    has_boundary = parcel and parcel.get('boundary_geom')
    has_footprints = sum(1 for s in structures if s.get('footprint_geom'))
    has_edge_geom = sum(1 for e in edges if e.get('edge_geom'))

    print(f'\nGeometry status:')
    print(f'  Parcel boundary_geom: {"YES" if has_boundary else "NULL — needs QGIS digitization"}')
    print(f'  Edge geometries: {has_edge_geom}/{len(edges)} populated')
    print(f'  Structure footprints: {has_footprints}/{len(structures)} populated')

    if not has_boundary and not has_footprints:
        print('\n  ** All geometry is NULL. Blender will use dimensional fallback placement. **')
        print('  ** Run QGIS digitization to populate footprint_geom for accurate rendering. **')


if __name__ == '__main__':
    main()
