"""
Blender Python script — 3D Property Digital Twin Render
160 Still Forest Drive, Cedar Creek TX 78612

Run headless: blender -b -P render_property.py
Run with GUI: blender -P render_property.py

Data source: property_data.json (generated by fetch_property_data.py from Supabase)
ALL geometry comes from the database — no hardcoded positions.
"""

import bpy
import bmesh
import json
import math
import os
import random
from mathutils import Vector

random.seed(42)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# 0.  CLEAR SCENE
# ---------------------------------------------------------------------------
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()
for col in bpy.data.collections:
    bpy.data.collections.remove(col)

# ---------------------------------------------------------------------------
# 1.  LOAD DATA from property_data.json (required)
# ---------------------------------------------------------------------------
data_path = os.path.join(SCRIPT_DIR, 'property_data.json')
if not os.path.exists(data_path):
    raise FileNotFoundError(
        f"property_data.json not found at {data_path}.\n"
        "Run: python3 fetch_property_data.py"
    )

with open(data_path) as f:
    db = json.load(f)

parcel = db['parcel']
edges_db = db['edges']
structures_db = db['structures']

print(f"Loaded {len(structures_db)} structures from database")

# ---------------------------------------------------------------------------
# 2.  COORDINATE SYSTEM — GPS to local feet
# ---------------------------------------------------------------------------
# Extract parcel boundary from DB
boundary_coords = parcel['boundary_geom']['coordinates'][0]  # GeoJSON ring
# Remove closing vertex (same as first)
if boundary_coords[-1] == boundary_coords[0]:
    boundary_coords = boundary_coords[:-1]

# Reference point — use SW-most corner as origin
# SW = min lon (most west) + min lat (most south)
ref_idx = min(range(len(boundary_coords)),
              key=lambda i: boundary_coords[i][0] + boundary_coords[i][1])
REF_LON, REF_LAT = boundary_coords[ref_idx]

DEG_TO_FT_LON = math.cos(math.radians(REF_LAT)) * 111_320 * 3.28084
DEG_TO_FT_LAT = 111_320 * 3.28084


def gps_to_ft(lon, lat):
    """Convert GPS (lon, lat) to local feet with reference point as (0, 0)."""
    return ((lon - REF_LON) * DEG_TO_FT_LON,
            (lat - REF_LAT) * DEG_TO_FT_LAT)


# Convert parcel boundary to feet
parcel_ft = [gps_to_ft(c[0], c[1]) for c in boundary_coords]

# Bounding box
all_x = [p[0] for p in parcel_ft]
all_y = [p[1] for p in parcel_ft]
min_x, max_x = min(all_x), max(all_x)
min_y, max_y = min(all_y), max(all_y)
cx = sum(all_x) / len(all_x)
cy = sum(all_y) / len(all_y)

print(f"Parcel: {len(parcel_ft)} vertices, "
      f"bbox ({min_x:.0f},{min_y:.0f}) to ({max_x:.0f},{max_y:.0f}), "
      f"centroid ({cx:.0f},{cy:.0f})")

# ---------------------------------------------------------------------------
# 3.  MATERIALS
# ---------------------------------------------------------------------------
def make_material(name, color, roughness=0.8, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat

MATERIALS = {
    'grass':       make_material("Grass",        (0.15, 0.35, 0.08, 1), roughness=0.95),
    'stone_frame': make_material("Stone/Frame",  (0.55, 0.50, 0.42, 1), roughness=0.85),
    'wood':        make_material("Wood",         (0.45, 0.30, 0.15, 1), roughness=0.75),
    'wood_deck':   make_material("Wood Deck",    (0.50, 0.35, 0.18, 1), roughness=0.70),
    'steel_red':   make_material("Red Steel",    (0.60, 0.12, 0.10, 1), roughness=0.4, metallic=0.7),
    'steel_beige': make_material("Beige Steel",  (0.65, 0.58, 0.42, 1), roughness=0.4, metallic=0.7),
    'steel_blue':  make_material("Blue Steel",   (0.15, 0.25, 0.50, 1), roughness=0.4, metallic=0.7),
    'steel':       make_material("Steel",        (0.45, 0.45, 0.48, 1), roughness=0.4, metallic=0.7),
    'rv':          make_material("RV White",     (0.85, 0.85, 0.82, 1), roughness=0.5, metallic=0.3),
    'roof':        make_material("Roof",         (0.30, 0.30, 0.32, 1), roughness=0.6, metallic=0.4),
    'road':        make_material("Road",         (0.25, 0.25, 0.25, 1), roughness=0.9),
    'gravel':      make_material("Gravel",       (0.40, 0.38, 0.34, 1), roughness=0.95),
    'setback':     make_material("Setback Line", (1.0, 0.3, 0.0, 0.5), roughness=0.5),
    'pool_water':  make_material("Pool Water",   (0.15, 0.50, 0.85, 1), roughness=0.3),
    'concrete':    make_material("Concrete",     (0.60, 0.58, 0.55, 1), roughness=0.8),
    'underground': make_material("Underground",  (0.35, 0.30, 0.25, 1), roughness=0.9),
    'tree_trunk':  make_material("TreeTrunk",    (0.30, 0.20, 0.10, 1), roughness=0.9),
    'tree_leaf':   make_material("TreeLeaf",     (0.10, 0.30, 0.05, 1), roughness=0.95),
}


def get_material(structure):
    """Pick material based on structure's material, color, and type fields."""
    mat_name = (structure.get('material') or '').lower()
    color = (structure.get('color') or '').lower()
    stype = structure.get('structure_type', '')

    # Color-specific containers
    if stype == 'container':
        if 'red' in color or 'red' in structure.get('name', '').lower():
            return MATERIALS['steel_red']
        if 'beige' in color or 'beige' in structure.get('name', '').lower():
            return MATERIALS['steel_beige']
        if 'blue' in color or '#3' in structure.get('name', ''):
            return MATERIALS['steel_blue']
        return MATERIALS['steel']

    # Material mapping
    mat_map = {
        'stone_frame': 'stone_frame',
        'stone': 'stone_frame',
        'wood': 'wood',
        'rv': 'rv',
        'steel_container': 'steel',
        'steel': 'steel',
        'gravel': 'gravel',
        'concrete': 'concrete',
        'underground': 'underground',
    }

    if mat_name in mat_map:
        return MATERIALS[mat_map[mat_name]]

    # Type-based fallback
    type_map = {
        'house': 'stone_frame',
        'outbuilding': 'wood',
        'deck': 'wood_deck',
        'sauna': 'wood',
        'trailer_rv': 'rv',
        'container': 'steel',
        'utility': 'underground',
    }
    return MATERIALS.get(type_map.get(stype, 'wood'), MATERIALS['wood'])


# ---------------------------------------------------------------------------
# 4.  GROUND PLANE — parcel boundary from DB
# ---------------------------------------------------------------------------
mesh = bpy.data.meshes.new("Parcel")
obj = bpy.data.objects.new("Parcel_Ground", mesh)
bpy.context.collection.objects.link(obj)

bm = bmesh.new()
verts = [bm.verts.new((x, y, 0)) for x, y in parcel_ft]
bm.faces.new(verts)
bm.to_mesh(mesh)
bm.free()
obj.data.materials.append(MATERIALS['grass'])

# ---------------------------------------------------------------------------
# 5.  ROAD — along the south edge (from DB edges)
# ---------------------------------------------------------------------------
south_edge = next((e for e in edges_db if e['edge_side'] == 'S'), None)
if south_edge and south_edge.get('edge_geom'):
    se_coords = south_edge['edge_geom']['coordinates']
    s_start = gps_to_ft(se_coords[0][0], se_coords[0][1])
    s_end = gps_to_ft(se_coords[1][0], se_coords[1][1])

    dx = s_end[0] - s_start[0]
    dy = s_end[1] - s_start[1]
    length = math.sqrt(dx**2 + dy**2)
    nx, ny = -dy / length, dx / length
    # Ensure normal points away from centroid (outward/south)
    if nx * (cx - s_start[0]) + ny * (cy - s_start[1]) > 0:
        nx, ny = -nx, -ny

    road_w = 30
    road_verts = [
        (s_start[0] - dx * 0.2, s_start[1] - dy * 0.2, -0.1),
        (s_end[0] + dx * 0.2, s_end[1] + dy * 0.2, -0.1),
        (s_end[0] + dx * 0.2 + nx * road_w, s_end[1] + dy * 0.2 + ny * road_w, -0.1),
        (s_start[0] - dx * 0.2 + nx * road_w, s_start[1] - dy * 0.2 + ny * road_w, -0.1),
    ]
    mesh_road = bpy.data.meshes.new("Road")
    obj_road = bpy.data.objects.new("Still_Forest_Dr", mesh_road)
    bpy.context.collection.objects.link(obj_road)
    bm = bmesh.new()
    rv = [bm.verts.new(v) for v in road_verts]
    bm.faces.new(rv)
    bm.to_mesh(mesh_road)
    bm.free()
    obj_road.data.materials.append(MATERIALS['road'])

# ---------------------------------------------------------------------------
# 6.  HELPER FUNCTIONS
# ---------------------------------------------------------------------------
def create_polygon_mesh(name, coords_ft, height, material, z_base=0):
    """Create extruded polygon from list of (x,y) coordinates."""
    mesh = bpy.data.meshes.new(name)
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)

    bm = bmesh.new()
    bottom_verts = [bm.verts.new((x, y, z_base)) for x, y in coords_ft]
    bm.faces.new(bottom_verts)

    if height > 0.2:
        top_verts = [bm.verts.new((x, y, z_base + height)) for x, y in coords_ft]
        bm.faces.new(top_verts)
        n = len(coords_ft)
        for i in range(n):
            j = (i + 1) % n
            bm.faces.new([bottom_verts[i], bottom_verts[j],
                         top_verts[j], top_verts[i]])

    bm.to_mesh(mesh)
    bm.free()
    obj.data.materials.append(material)
    return obj


def create_roof_from_footprint(name, coords_ft, h_base, h_peak, material):
    """Create a gable roof over a footprint polygon, aligned with property angle."""
    xs = [c[0] for c in coords_ft]
    ys = [c[1] for c in coords_ft]
    cx_r = (min(xs) + max(xs)) / 2
    cy_r = (min(ys) + max(ys)) / 2

    # Find the longest edge of the footprint to determine ridge direction
    max_edge_len = 0
    ridge_angle = 0
    for i in range(len(coords_ft)):
        j = (i + 1) % len(coords_ft)
        dx = coords_ft[j][0] - coords_ft[i][0]
        dy = coords_ft[j][1] - coords_ft[i][1]
        edge_len = math.sqrt(dx**2 + dy**2)
        if edge_len > max_edge_len:
            max_edge_len = edge_len
            ridge_angle = math.atan2(dy, dx)

    # Half-widths: along ridge and perpendicular
    hl = max_edge_len / 2  # along ridge
    # Find width perpendicular to ridge
    cos_a = math.cos(ridge_angle)
    sin_a = math.sin(ridge_angle)
    perp_dists = []
    for c in coords_ft:
        dx = c[0] - cx_r
        dy = c[1] - cy_r
        perp = -dx * sin_a + dy * cos_a
        perp_dists.append(perp)
    hw = (max(perp_dists) - min(perp_dists)) / 2

    mesh = bpy.data.meshes.new(name + "_roof")
    obj = bpy.data.objects.new(name + "_Roof", mesh)
    bpy.context.collection.objects.link(obj)

    bm = bmesh.new()
    v0 = bm.verts.new((-hl, -hw, h_base))
    v1 = bm.verts.new((hl, -hw, h_base))
    v2 = bm.verts.new((hl, hw, h_base))
    v3 = bm.verts.new((-hl, hw, h_base))
    v4 = bm.verts.new((-hl, 0, h_base + h_peak))
    v5 = bm.verts.new((hl, 0, h_base + h_peak))

    bm.faces.new([v0, v1, v5, v4])   # front slope
    bm.faces.new([v1, v2, v5])        # right gable
    bm.faces.new([v2, v3, v4, v5])    # back slope
    bm.faces.new([v3, v0, v4])        # left gable

    bm.to_mesh(mesh)
    bm.free()
    obj.location = (cx_r, cy_r, 0)
    obj.rotation_euler.z = ridge_angle
    obj.data.materials.append(material)
    return obj


# ---------------------------------------------------------------------------
# 7.  STRUCTURES — all from database footprint_geom
# ---------------------------------------------------------------------------
structure_centers = []  # for tree collision avoidance

for s in structures_db:
    name = s['name'].replace(' ', '_').replace('#', '').replace('(', '').replace(')', '')
    stype = s.get('structure_type', 'other')
    height = float(s.get('height_ft') or 0)
    roof_type = s.get('roof_type')
    material = get_material(s)

    # Skip utility structures that are underground
    if s.get('material') == 'underground' and height == 0:
        continue

    # Get footprint from DB geometry
    geom = s.get('footprint_geom')
    if not geom:
        print(f"  SKIP {s['name']} — no footprint_geom")
        continue

    # Parse GeoJSON polygon coordinates
    ring = geom['coordinates'][0]
    if ring[-1] == ring[0]:
        ring = ring[:-1]
    coords_ft = [gps_to_ft(c[0], c[1]) for c in ring]

    # Compute centroid for this structure
    scx = sum(c[0] for c in coords_ft) / len(coords_ft)
    scy = sum(c[1] for c in coords_ft) / len(coords_ft)
    structure_centers.append((scx, scy))

    print(f"  {s['name']}: {len(coords_ft)} verts, height={height}, "
          f"center=({scx:.0f},{scy:.0f})")

    # Special handling for pool
    if 'pool' in s['name'].lower() or 'swim' in s['name'].lower():
        # Pool rim (concrete deck)
        create_polygon_mesh(name + "_Rim", coords_ft, 1.0,
                          MATERIALS['concrete'], z_base=0.02)
        # Pool water (inset, flush on top)
        margin = 2  # ft inset
        pool_cx = sum(c[0] for c in coords_ft) / len(coords_ft)
        pool_cy = sum(c[1] for c in coords_ft) / len(coords_ft)
        inset = []
        for c in coords_ft:
            dx = c[0] - pool_cx
            dy = c[1] - pool_cy
            dist = math.sqrt(dx**2 + dy**2)
            if dist > 0:
                scale = (dist - margin) / dist
                inset.append((pool_cx + dx * scale, pool_cy + dy * scale))
            else:
                inset.append(c)
        create_polygon_mesh(name + "_Water", inset, 0.2,
                          MATERIALS['pool_water'], z_base=1.1)
        continue

    # Special handling for driveway/gravel
    if 'driveway' in s['name'].lower() or 'gravel' in s['name'].lower():
        create_polygon_mesh(name, coords_ft, 0.15, MATERIALS['gravel'], z_base=0.02)
        continue

    # Special handling for deck (low height)
    if stype == 'deck':
        create_polygon_mesh(name, coords_ft, max(height, 1.5),
                          MATERIALS['wood_deck'], z_base=0.05)
        continue

    # Regular structure — extrude footprint to height
    if height < 1:
        height = 8  # default height if not specified

    create_polygon_mesh(name, coords_ft, height, material)

    # Add roof if applicable
    if roof_type and roof_type not in ('none', 'flat'):
        peak = 4 if height < 12 else 6
        create_roof_from_footprint(name, coords_ft, height, peak,
                                  MATERIALS['roof'])

# ---------------------------------------------------------------------------
# 8.  SETBACK LINES — from DB edge geometries
# ---------------------------------------------------------------------------
for edge in edges_db:
    geom = edge.get('edge_geom')
    if not geom:
        continue

    side = edge['edge_side']
    setback_ft = float(edge.get('setback_required_ft') or 10)
    coords = geom['coordinates']
    p_start = gps_to_ft(coords[0][0], coords[0][1])
    p_end = gps_to_ft(coords[1][0], coords[1][1])

    dx = p_end[0] - p_start[0]
    dy = p_end[1] - p_start[1]
    length = math.sqrt(dx**2 + dy**2)
    if length < 0.01:
        continue

    nx, ny = -dy / length, dx / length
    mid_x = (p_start[0] + p_end[0]) / 2
    mid_y = (p_start[1] + p_end[1]) / 2
    if nx * (cx - mid_x) + ny * (cy - mid_y) < 0:
        nx, ny = -nx, -ny

    s1 = (p_start[0] + nx * setback_ft, p_start[1] + ny * setback_ft, 0.05)
    s2 = (p_end[0] + nx * setback_ft, p_end[1] + ny * setback_ft, 0.05)

    strip_w = 0.5
    perp_x = -dy / length * strip_w
    perp_y = dx / length * strip_w

    mesh_sb = bpy.data.meshes.new(f"Setback_{side}")
    obj_sb = bpy.data.objects.new(f"Setback_{side}", mesh_sb)
    bpy.context.collection.objects.link(obj_sb)
    bm = bmesh.new()
    sv = [
        bm.verts.new((s1[0] - perp_x, s1[1] - perp_y, 0.05)),
        bm.verts.new((s2[0] - perp_x, s2[1] - perp_y, 0.05)),
        bm.verts.new((s2[0] + perp_x, s2[1] + perp_y, 0.05)),
        bm.verts.new((s1[0] + perp_x, s1[1] + perp_y, 0.05)),
    ]
    bm.faces.new(sv)
    bm.to_mesh(mesh_sb)
    bm.free()
    obj_sb.data.materials.append(MATERIALS['setback'])

# ---------------------------------------------------------------------------
# 9.  TREES — west-biased per survey (heavy coverage on west half)
# ---------------------------------------------------------------------------
def point_in_polygon(px, py, polygon):
    """Ray-casting point-in-polygon test."""
    n = len(polygon)
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        if ((yi > py) != (yj > py)) and (px < (xj - xi) * (py - yi) / (yj - yi) + xi):
            inside = not inside
        j = i
    return inside


for i in range(40):
    placed = False
    for _ in range(150):
        # 70% of trees in west half (survey shows heavy tree cover on west)
        if random.random() < 0.70:
            rx = random.uniform(min_x + 15, cx - 15)
        else:
            rx = random.uniform(cx + 10, max_x - 20)
        ry = random.uniform(min_y + 25, max_y - 15)

        # Must be inside parcel boundary
        if not point_in_polygon(rx, ry, parcel_ft):
            continue

        ok = True
        for sc in structure_centers:
            if math.sqrt((rx - sc[0])**2 + (ry - sc[1])**2) < 40:
                ok = False
                break
        if ok:
            placed = True
            break

    if not placed:
        continue

    trunk_h = random.uniform(20, 38)
    crown_r = random.uniform(8, 15)

    bpy.ops.mesh.primitive_cylinder_add(
        radius=random.uniform(0.6, 1.2), depth=trunk_h,
        location=(rx, ry, trunk_h / 2))
    trunk = bpy.context.active_object
    trunk.name = f"TreeTrunk_{i}"
    trunk.data.materials.append(MATERIALS['tree_trunk'])

    bpy.ops.mesh.primitive_ico_sphere_add(
        radius=crown_r, subdivisions=2,
        location=(rx, ry, trunk_h + crown_r * 0.5))
    crown = bpy.context.active_object
    crown.name = f"TreeCrown_{i}"
    crown.scale = (
        random.uniform(0.8, 1.2),
        random.uniform(0.8, 1.2),
        random.uniform(0.7, 1.0),
    )
    crown.data.materials.append(MATERIALS['tree_leaf'])

# ---------------------------------------------------------------------------
# 10. LIGHTING
# ---------------------------------------------------------------------------
bpy.ops.object.light_add(type='SUN', location=(0, 0, 200))
sun = bpy.context.active_object
sun.name = "Sun"
sun.data.energy = 5
sun.data.angle = math.radians(0.5)
sun.rotation_euler = (math.radians(45), math.radians(15), math.radians(-30))

bpy.ops.object.light_add(type='SUN', location=(0, 0, 200))
fill = bpy.context.active_object
fill.name = "Fill_Light"
fill.data.energy = 1.5
fill.rotation_euler = (math.radians(70), math.radians(-40), math.radians(60))

# ---------------------------------------------------------------------------
# 11. WORLD (sky)
# ---------------------------------------------------------------------------
world = bpy.data.worlds.new("PropertyWorld")
bpy.context.scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes["Background"]
bg.inputs["Color"].default_value = (0.45, 0.60, 0.85, 1)
bg.inputs["Strength"].default_value = 0.8

# ---------------------------------------------------------------------------
# 12. CAMERA — bird's-eye perspective view
# ---------------------------------------------------------------------------
# Camera from ESE looking WNW — angled to match survey plat perspective
cam_x = cx + 380
cam_y = cy - 200
cam_z = 480

bpy.ops.object.camera_add(location=(cam_x, cam_y, cam_z))
cam = bpy.context.active_object
cam.name = "BirdsEye"

direction = Vector((cx, cy, 0)) - cam.location
rot_quat = direction.to_track_quat('-Z', 'Y')
cam.rotation_euler = rot_quat.to_euler()

cam.data.lens = 28
cam.data.clip_end = 2000
bpy.context.scene.camera = cam

# ---------------------------------------------------------------------------
# 13. RENDER SETTINGS
# ---------------------------------------------------------------------------
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
scene.cycles.samples = 64
scene.cycles.use_denoising = True
scene.render.resolution_x = 2560
scene.render.resolution_y = 1440
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = 'PNG'

output_path = os.path.join(SCRIPT_DIR, "render_property.png")
scene.render.filepath = output_path

blend_path = os.path.join(SCRIPT_DIR, "property_digital_twin.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_path)

rendered = len(structure_centers)
total = len(structures_db)
skipped = total - rendered
print(f"\n{'='*60}")
print(f"Scene built from database: {rendered}/{total} structures rendered "
      f"({skipped} skipped — no footprint_geom)")
print(f"Blend saved: {blend_path}")
print(f"Render to:   {output_path}")
print(f"To render:   blender -b {blend_path} -o {output_path} -F PNG -f 1")
print(f"{'='*60}\n")

bpy.ops.render.render(write_still=True)
print(f"Render complete: {output_path}")
