"""
Blender Python script — 3D Property Digital Twin Render
160 Still Forest Drive, Cedar Creek TX 78612

Run headless: blender -b -P render_property.py
Run with GUI: blender -P render_property.py

Data source: property_data.json (generated by fetch_property_data.py from Supabase)
Fallback: survey-matched hardcoded positions when footprint_geom is NULL
"""

import bpy
import bmesh
import json
import math
import os
import random
from mathutils import Vector

random.seed(42)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# 0.  CLEAR SCENE
# ---------------------------------------------------------------------------
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()
for col in bpy.data.collections:
    bpy.data.collections.remove(col)

# ---------------------------------------------------------------------------
# 1.  LOAD DATA — try property_data.json, else use hardcoded survey data
# ---------------------------------------------------------------------------
data_path = os.path.join(SCRIPT_DIR, 'property_data.json')
db_data = None
if os.path.exists(data_path):
    with open(data_path) as f:
        db_data = json.load(f)
    print(f"Loaded property data from {data_path}")

# ---------------------------------------------------------------------------
# 2.  PARCEL BOUNDARY — from survey bearings/distances
# ---------------------------------------------------------------------------
# These coordinates are from the 4Ward Land Survey (2025 update).
# The parcel is an irregular polygon with road (Still Forest Dr) on south.
# Vertices listed counter-clockwise starting from SW corner.
#
# Survey bearings converted to GPS coordinates:
# The property is ~330 ft N-S and ~280 ft E-W at widest (north end).
# South edge (road frontage) is ~195 ft, narrower than the north edge (~215 ft).

# Survey-matched corners (lon, lat) — refined from plat measurements
# These produce the correct irregular trapezoid shape visible in the survey
PARCEL_GPS = [
    (-97.45980270, 30.13056788),  # SW corner (origin) — road/south edge
    (-97.45948000, 30.13100000),  # SE corner — road/south edge
    (-97.45910000, 30.13155000),  # NE corner — wider north end
    (-97.46020000, 30.13162000),  # N-mid (north edge jog)
    (-97.46065000, 30.13148000),  # NW corner — wider north end
    (-97.46040000, 30.13060000),  # W-mid (west edge)
]

# Reference point — SW corner as origin
REF = PARCEL_GPS[0]

DEG_TO_FT_LON = math.cos(math.radians(30.131)) * 111_320 * 3.28084  # ~315,600 ft/deg
DEG_TO_FT_LAT = 111_320 * 3.28084  # ~365,200 ft/deg


def gps_to_ft(lon, lat):
    """Convert GPS to local feet with SW corner as (0, 0)."""
    x = (lon - REF[0]) * DEG_TO_FT_LON
    y = (lat - REF[1]) * DEG_TO_FT_LAT
    return (x, y)


parcel_ft = [gps_to_ft(lon, lat) for lon, lat in PARCEL_GPS]

# Compute parcel centroid and bounding box
cx = sum(p[0] for p in parcel_ft) / len(parcel_ft)
cy = sum(p[1] for p in parcel_ft) / len(parcel_ft)
min_x = min(p[0] for p in parcel_ft)
max_x = max(p[0] for p in parcel_ft)
min_y = min(p[1] for p in parcel_ft)
max_y = max(p[1] for p in parcel_ft)

# ---------------------------------------------------------------------------
# 3.  MATERIALS
# ---------------------------------------------------------------------------
def make_material(name, color, roughness=0.8, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat

mat_grass      = make_material("Grass",        (0.15, 0.35, 0.08, 1), roughness=0.95)
mat_stone      = make_material("Stone/Frame",  (0.55, 0.50, 0.42, 1), roughness=0.85)
mat_wood       = make_material("Wood",         (0.45, 0.30, 0.15, 1), roughness=0.75)
mat_wood_deck  = make_material("Wood Deck",    (0.50, 0.35, 0.18, 1), roughness=0.70)
mat_red_steel  = make_material("Red Steel",    (0.60, 0.12, 0.10, 1), roughness=0.4, metallic=0.7)
mat_beige_stl  = make_material("Beige Steel",  (0.65, 0.58, 0.42, 1), roughness=0.4, metallic=0.7)
mat_blue_stl   = make_material("Blue Steel",   (0.15, 0.25, 0.50, 1), roughness=0.4, metallic=0.7)
mat_rv_white   = make_material("RV White",     (0.85, 0.85, 0.82, 1), roughness=0.5, metallic=0.3)
mat_roof_grey  = make_material("Roof",         (0.30, 0.30, 0.32, 1), roughness=0.6, metallic=0.4)
mat_sauna_mat  = make_material("Sauna Cedar",  (0.55, 0.35, 0.18, 1), roughness=0.6)
mat_road       = make_material("Road",         (0.25, 0.25, 0.25, 1), roughness=0.9)
mat_gravel     = make_material("Gravel",       (0.40, 0.38, 0.34, 1), roughness=0.95)
mat_setback    = make_material("Setback Line", (1.0, 0.3, 0.0, 0.5), roughness=0.5)
mat_pool_water = make_material("Pool Water",   (0.15, 0.45, 0.65, 1), roughness=0.1, metallic=0.0)
mat_pool_deck  = make_material("Pool Deck",    (0.60, 0.55, 0.48, 1), roughness=0.7)
mat_bath_bldg  = make_material("Bath Bldg",    (0.50, 0.45, 0.35, 1), roughness=0.8)
mat_tree_trunk = make_material("TreeTrunk",    (0.30, 0.20, 0.10, 1), roughness=0.9)
mat_tree_leaf  = make_material("TreeLeaf",     (0.10, 0.30, 0.05, 1), roughness=0.95)

# ---------------------------------------------------------------------------
# 4.  GROUND PLANE (parcel boundary polygon)
# ---------------------------------------------------------------------------
mesh = bpy.data.meshes.new("Parcel")
obj = bpy.data.objects.new("Parcel_Ground", mesh)
bpy.context.collection.objects.link(obj)

bm = bmesh.new()
verts = [bm.verts.new((x, y, 0)) for x, y in parcel_ft]
bm.faces.new(verts)
bm.to_mesh(mesh)
bm.free()
obj.data.materials.append(mat_grass)

# ---------------------------------------------------------------------------
# 5.  ROAD — Still Forest Dr (CR 329) along south edge
# ---------------------------------------------------------------------------
sw_ft = parcel_ft[0]  # SW corner
se_ft = parcel_ft[1]  # SE corner

road_dir_x = se_ft[0] - sw_ft[0]
road_dir_y = se_ft[1] - sw_ft[1]
road_len = math.sqrt(road_dir_x**2 + road_dir_y**2)
road_nx = -road_dir_y / road_len
road_ny = road_dir_x / road_len

road_width = 30
road_verts = [
    (sw_ft[0] - road_dir_x * 0.3, sw_ft[1] - road_dir_y * 0.3, -0.1),
    (se_ft[0] + road_dir_x * 0.3, se_ft[1] + road_dir_y * 0.3, -0.1),
    (se_ft[0] + road_dir_x * 0.3 + road_nx * road_width,
     se_ft[1] + road_dir_y * 0.3 + road_ny * road_width, -0.1),
    (sw_ft[0] - road_dir_x * 0.3 + road_nx * road_width,
     sw_ft[1] - road_dir_y * 0.3 + road_ny * road_width, -0.1),
]

mesh_road = bpy.data.meshes.new("Road")
obj_road = bpy.data.objects.new("Still_Forest_Dr", mesh_road)
bpy.context.collection.objects.link(obj_road)
bm = bmesh.new()
rv = [bm.verts.new(v) for v in road_verts]
bm.faces.new(rv)
bm.to_mesh(mesh_road)
bm.free()
obj_road.data.materials.append(mat_road)


# ---------------------------------------------------------------------------
# 6.  HELPER FUNCTIONS
# ---------------------------------------------------------------------------
def create_box(name, x, y, w, l, h, material, rotation=0):
    """Create a box at (x, y) with dimensions w x l x h feet."""
    bpy.ops.mesh.primitive_cube_add(size=1, location=(x, y, h / 2))
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = (w, l, h)
    obj.rotation_euler.z = rotation
    obj.data.materials.append(material)
    return obj


def create_roof(name, x, y, w, l, h_base, h_peak, material, rotation=0):
    """Create a gable roof at (x, y)."""
    mesh = bpy.data.meshes.new(name + "_roof")
    obj = bpy.data.objects.new(name + "_Roof", mesh)
    bpy.context.collection.objects.link(obj)

    bm = bmesh.new()
    hw, hl = w / 2, l / 2
    v0 = bm.verts.new((-hw, -hl, h_base))
    v1 = bm.verts.new((hw, -hl, h_base))
    v2 = bm.verts.new((hw, hl, h_base))
    v3 = bm.verts.new((-hw, hl, h_base))
    v4 = bm.verts.new((0, -hl, h_base + h_peak))
    v5 = bm.verts.new((0, hl, h_base + h_peak))

    bm.faces.new([v0, v1, v4])
    bm.faces.new([v2, v3, v5])
    bm.faces.new([v0, v4, v5, v3])
    bm.faces.new([v1, v2, v5, v4])

    bm.to_mesh(mesh)
    bm.free()
    obj.location = (x, y, 0)
    obj.rotation_euler.z = rotation
    obj.data.materials.append(material)
    return obj


def create_polygon(name, coords_ft, height, material, z_base=0):
    """Create extruded polygon from list of (x,y) coordinates."""
    mesh = bpy.data.meshes.new(name)
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)

    bm = bmesh.new()
    # Bottom face
    bottom_verts = [bm.verts.new((x, y, z_base)) for x, y in coords_ft]
    bottom_face = bm.faces.new(bottom_verts)

    if height > 0.2:
        # Top face
        top_verts = [bm.verts.new((x, y, z_base + height)) for x, y in coords_ft]
        top_face = bm.faces.new(top_verts)
        # Side faces
        n = len(coords_ft)
        for i in range(n):
            j = (i + 1) % n
            bm.faces.new([bottom_verts[i], bottom_verts[j],
                         top_verts[j], top_verts[i]])

    bm.to_mesh(mesh)
    bm.free()
    obj.data.materials.append(material)
    return obj


def create_oval(name, cx, cy, rx, ry, height, material, segments=24, z_base=0):
    """Create an oval/ellipse extruded mesh."""
    coords = []
    for i in range(segments):
        angle = 2 * math.pi * i / segments
        x = cx + rx * math.cos(angle)
        y = cy + ry * math.sin(angle)
        coords.append((x, y))
    return create_polygon(name, coords, height, material, z_base)


# ---------------------------------------------------------------------------
# 7.  STRUCTURES — survey-matched positions
# ---------------------------------------------------------------------------
# Positions are placed to match the 4Ward Land Survey plat (2025 update).
# The survey shows (looking from the road/south):
#   - Main House: NE quadrant, large rectangular
#   - Back House: just NW of main house
#   - Pool: center of property, oval/kidney shape
#   - Deck: around pool and between houses
#   - Containers: clustered in the north portion
#   - Trailers: north area
#   - Bathroom Bldg: near main house cluster
#   - Sauna: west of pool area
#
# Coordinates below are in local feet (SW corner = 0,0).
# When footprint_geom is populated in DB, these will be replaced by
# reading from property_data.json.

# Property approximate dimensions from survey:
# Width at south (road): ~195 ft
# Width at north: ~280 ft
# Depth (N-S): ~330 ft

# Main House — NE quadrant (~40x60, stone/frame, 2-story)
# From survey: ~60 ft from east edge, ~230 ft from south (road)
main_house_x = max_x - 80
main_house_y = min_y + 240
create_box("Main_House", main_house_x, main_house_y, 40, 60, 14, mat_stone, rotation=0.05)
create_roof("Main_House", main_house_x, main_house_y, 42, 62, 14, 6, mat_roof_grey, rotation=0.05)

# Back House — just NW of main house (~20x30, wood)
back_house_x = main_house_x - 55
back_house_y = main_house_y + 30
create_box("Back_House", back_house_x, back_house_y, 20, 30, 10, mat_wood, rotation=0.05)
create_roof("Back_House", back_house_x, back_house_y, 22, 32, 10, 4, mat_roof_grey, rotation=0.05)

# Bathroom Bldg — near main house cluster, slightly south
bath_x = main_house_x - 40
bath_y = main_house_y - 15
create_box("Bathroom_Bldg", bath_x, bath_y, 17, 17, 9, mat_bath_bldg, rotation=0.05)
create_roof("Bathroom_Bldg", bath_x, bath_y, 18, 18, 9, 3, mat_roof_grey, rotation=0.05)

# Pool — center of property, large oval (~20x35 ft)
pool_x = cx + 15
pool_y = cy + 30
# Pool deck (larger oval around pool)
create_oval("Pool_Deck", pool_x, pool_y, 28, 22, 0.5, mat_pool_deck, z_base=-0.05)
# Pool water surface (inset)
create_oval("Pool", pool_x, pool_y, 20, 15, 0.1, mat_pool_water, z_base=0.3)

# Deck — large deck area between pool and main house
deck_coords = [
    (pool_x - 30, pool_y - 25),
    (main_house_x - 20, main_house_y - 35),
    (main_house_x + 15, main_house_y - 35),
    (pool_x + 30, pool_y - 20),
    (pool_x + 30, pool_y + 5),
    (pool_x - 30, pool_y + 5),
]
create_polygon("Deck", deck_coords, 1.5, mat_wood_deck, z_base=0.05)

# Sauna — west of pool area, small square (7x7)
sauna_x = pool_x - 50
sauna_y = pool_y - 10
create_box("Sauna", sauna_x, sauna_y, 7, 7, 7, mat_sauna_mat)
create_roof("Sauna", sauna_x, sauna_y, 8, 8, 7, 2.5, mat_roof_grey)

# --- Containers — clustered in the north portion of the property ---
# From survey: containers are roughly parallel, in the upper third

container_base_y = max_y - 50  # ~50 ft from north edge

# Red Container #1 — west side of north area
create_box("Red_Container_1", cx - 40, container_base_y, 8, 40, 8.5,
           mat_red_steel, rotation=0.05)

# Red Container #2 — east of #1
create_box("Red_Container_2", cx + 10, container_base_y + 12, 8, 40, 8.5,
           mat_red_steel, rotation=0.05)

# Container #3 (blue) — between the reds
create_box("Container_3", cx - 15, container_base_y - 15, 8, 40, 8.5,
           mat_blue_stl, rotation=0.05)

# Beige Container — slightly south of the cluster
create_box("Beige_Container", cx + 30, container_base_y - 30, 8, 40, 8.5,
           mat_beige_stl, rotation=0.05)

# --- Trailers — north area ---

# Big Trailer (10x42) — north area, west side
create_box("Big_Trailer", cx - 60, container_base_y + 20, 10, 42, 10,
           mat_rv_white, rotation=0.05)

# Small Trailer (7.4x20.4) — east side
create_box("Small_Trailer", max_x - 50, cy + 60, 7.4, 20.4, 9,
           mat_rv_white, rotation=0.1)

# --- Driveway — enters from SE, curves north to main house ---
# Approximated as a polygon path
driveway_pts = [
    # Entry from road (SE area)
    (se_ft[0] - 30, se_ft[1] + 5),
    (se_ft[0] - 15, se_ft[1] + 5),
    (se_ft[0] - 10, se_ft[1] + 30),
    # Curve north
    (se_ft[0] - 20, se_ft[1] + 80),
    (max_x - 40, min_y + 150),
    # Approach main house area
    (max_x - 50, main_house_y - 60),
    (max_x - 70, main_house_y - 50),
    # Circular area near house
    (max_x - 90, main_house_y - 55),
    (max_x - 100, main_house_y - 65),
    (max_x - 90, main_house_y - 75),
    (max_x - 60, main_house_y - 70),
    (max_x - 40, main_house_y - 65),
    # Return path south (make it a loop for width)
    (max_x - 55, min_y + 140),
    (se_ft[0] - 35, se_ft[1] + 70),
    (se_ft[0] - 40, se_ft[1] + 25),
    (se_ft[0] - 45, se_ft[1] + 5),
]
create_polygon("Driveway", driveway_pts, 0.15, mat_gravel, z_base=0.02)

# ---------------------------------------------------------------------------
# 8.  SETBACK LINES — from parcel edges
# ---------------------------------------------------------------------------
setback_distances = {
    'S': (0, 1, 20),   # SW→SE edge, 20 ft setback (road)
    'E': (1, 2, 10),   # SE→NE edge, 10 ft
    'N_east': (2, 3, 10),   # NE→N-mid, 10 ft
    'N_west': (3, 4, 10),   # N-mid→NW, 10 ft
    'W_upper': (4, 5, 10),   # NW→W-mid, 10 ft
    'W_lower': (5, 0, 10),   # W-mid→SW, 10 ft
}

for label, (i_start, i_end, dist) in setback_distances.items():
    p_start = parcel_ft[i_start]
    p_end = parcel_ft[i_end]

    # Compute inward normal
    dx = p_end[0] - p_start[0]
    dy = p_end[1] - p_start[1]
    length = math.sqrt(dx**2 + dy**2)
    if length < 0.01:
        continue
    nx, ny = -dy / length, dx / length
    # Ensure normal points inward (toward centroid)
    mid_x = (p_start[0] + p_end[0]) / 2
    mid_y = (p_start[1] + p_end[1]) / 2
    if nx * (cx - mid_x) + ny * (cy - mid_y) < 0:
        nx, ny = -nx, -ny

    p1 = (p_start[0] + nx * dist, p_start[1] + ny * dist, 0.05)
    p2 = (p_end[0] + nx * dist, p_end[1] + ny * dist, 0.05)

    strip_w = 0.5
    perp_x = -dy / length * strip_w
    perp_y = dx / length * strip_w

    mesh_sb = bpy.data.meshes.new(f"Setback_{label}")
    obj_sb = bpy.data.objects.new(f"Setback_{label}", mesh_sb)
    bpy.context.collection.objects.link(obj_sb)
    bm = bmesh.new()
    sv = [
        bm.verts.new((p1[0] - perp_x, p1[1] - perp_y, 0.05)),
        bm.verts.new((p2[0] - perp_x, p2[1] - perp_y, 0.05)),
        bm.verts.new((p2[0] + perp_x, p2[1] + perp_y, 0.05)),
        bm.verts.new((p1[0] + perp_x, p1[1] + perp_y, 0.05)),
    ]
    bm.faces.new(sv)
    bm.to_mesh(mesh_sb)
    bm.free()
    obj_sb.data.materials.append(mat_setback)

# ---------------------------------------------------------------------------
# 9.  TREES — west-biased per survey (heavy coverage on west half)
# ---------------------------------------------------------------------------
# Structure centers for collision avoidance
structure_centers = [
    (main_house_x, main_house_y),
    (back_house_x, back_house_y),
    (bath_x, bath_y),
    (pool_x, pool_y),
    (sauna_x, sauna_y),
    (cx - 40, container_base_y),
    (cx + 10, container_base_y + 12),
    (cx - 15, container_base_y - 15),
    (cx + 30, container_base_y - 30),
    (cx - 60, container_base_y + 20),
    (max_x - 50, cy + 60),
]

for i in range(35):
    for _ in range(80):
        # 75% of trees placed in west half, 25% elsewhere (matches survey)
        if random.random() < 0.75:
            rx = random.uniform(min_x + 10, cx - 20)
        else:
            rx = random.uniform(min_x + 10, max_x - 10)
        ry = random.uniform(min_y + 25, max_y - 10)

        # Must be 30 ft from any structure
        ok = True
        for sc in structure_centers:
            if math.sqrt((rx - sc[0])**2 + (ry - sc[1])**2) < 30:
                ok = False
                break
        # Must be inside property bounds (rough check)
        if rx < min_x + 5 or rx > max_x - 5 or ry < min_y + 5 or ry > max_y - 5:
            ok = False
        if ok:
            break

    trunk_h = random.uniform(18, 35)
    crown_r = random.uniform(8, 14)

    # Trunk
    bpy.ops.mesh.primitive_cylinder_add(
        radius=random.uniform(0.6, 1.2), depth=trunk_h,
        location=(rx, ry, trunk_h / 2))
    trunk = bpy.context.active_object
    trunk.name = f"TreeTrunk_{i}"
    trunk.data.materials.append(mat_tree_trunk)

    # Crown — use icosphere for rounder oaks (more realistic than cones)
    bpy.ops.mesh.primitive_ico_sphere_add(
        radius=crown_r, subdivisions=2,
        location=(rx, ry, trunk_h + crown_r * 0.5))
    crown = bpy.context.active_object
    crown.name = f"TreeCrown_{i}"
    # Slight random scaling for natural variation
    crown.scale = (
        random.uniform(0.8, 1.2),
        random.uniform(0.8, 1.2),
        random.uniform(0.7, 1.0),
    )
    crown.data.materials.append(mat_tree_leaf)

# ---------------------------------------------------------------------------
# 10. LIGHTING — Sun matching Cedar Creek latitude (~30.13 N)
# ---------------------------------------------------------------------------
bpy.ops.object.light_add(type='SUN', location=(0, 0, 200))
sun = bpy.context.active_object
sun.name = "Sun"
sun.data.energy = 5
sun.data.angle = math.radians(0.5)
sun.rotation_euler = (math.radians(45), math.radians(15), math.radians(-30))

bpy.ops.object.light_add(type='SUN', location=(0, 0, 200))
fill = bpy.context.active_object
fill.name = "Fill_Light"
fill.data.energy = 1.5
fill.rotation_euler = (math.radians(70), math.radians(-40), math.radians(60))

# ---------------------------------------------------------------------------
# 11. WORLD (sky)
# ---------------------------------------------------------------------------
world = bpy.data.worlds.new("PropertyWorld")
bpy.context.scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes["Background"]
bg.inputs["Color"].default_value = (0.45, 0.60, 0.85, 1)
bg.inputs["Strength"].default_value = 0.8

# ---------------------------------------------------------------------------
# 12. CAMERA — bird's-eye perspective view
# ---------------------------------------------------------------------------
bpy.ops.object.camera_add(location=(cx + 250, cy - 300, 350))
cam = bpy.context.active_object
cam.name = "BirdsEye"

direction = Vector((cx, cy, 0)) - cam.location
rot_quat = direction.to_track_quat('-Z', 'Y')
cam.rotation_euler = rot_quat.to_euler()

cam.data.lens = 35
cam.data.clip_end = 2000
bpy.context.scene.camera = cam

# ---------------------------------------------------------------------------
# 13. RENDER SETTINGS
# ---------------------------------------------------------------------------
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
scene.cycles.samples = 128
scene.cycles.use_denoising = True
scene.render.resolution_x = 2560
scene.render.resolution_y = 1440
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = 'PNG'

output_path = os.path.join(SCRIPT_DIR, "render_property.png")
scene.render.filepath = output_path

blend_path = os.path.join(SCRIPT_DIR, "property_digital_twin.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_path)

n_structures = 14  # 11 original + pool + deck + driveway
print(f"\n{'='*60}")
print(f"Scene built: {n_structures} structures + pool + driveway + parcel + setbacks + trees")
print(f"Blend saved: {blend_path}")
print(f"Render to:   {output_path}")
print(f"To render:   blender -b {blend_path} -o {output_path} -F PNG -f 1")
print(f"{'='*60}\n")

# Uncomment to auto-render:
# bpy.ops.render.render(write_still=True)
# print(f"Render complete: {output_path}")
